### PR TITLE
Lots of UX work

### PR DESCRIPTION
**Pull request by wibblymat**
- Removed the unnecessary image view
- Improved performance of edit
  - Deferred save
  - Save as JPEG
- Added drag and drop to the upload view
- Changed UX for edit filters - small button toolbar selects effect, slider(s)
  then pop up
- Try to fit the edited image to the screen properly

### CODE REVIEW

**Comment by mustafa-x** [comment]
Whats the best way for me to run this? I guess it would be good for me to do a UX review or sorts on both desktop and mobile.

**Comment by wibblymat** [comment]
A great question that I should have given more thought to!

Luckily, in this case the app at https://snapshot-stable.firebaseapp.com/ is in the same state as this PR, so you can review it there.

**Comment by mustafa-x** [comment]
Below are some notes I have made so far. 

**General** 
-The url bar is the same as the background, I would make it darker if possible just to frame the app a bit. 
- The app is a little sluggish, we spoke about this, could be the IDB api you are using to save and reload images. Because the camera will have its own photo quality setting set up by the user, is there a way to compress the images for display purposes to speed it up? 

**First screen / on launch** 
screenshot_20170808-114618
- Not sure what the app is but It is asking access to my camera. I would probably do a start up screen that explains what the app is and that it will as for permission first. 
- Also, as the Android UI is blocking the screen, all I am seeing it a grey screen. 
- There is a is a floating 'X' button. It feels like this would be the second screen you would show in an order, so the first one would be explaining the app, then you come here. 
- There is a second dialogue appearing, only once I allowed access to my camera did I realize it is a dialogue asking me to add to the home screen. 

**First screen / on launch - Adding to home screen** 
screenshot_20170808-114923
- You ask for this right away, I would delay asking if a user wants to add to home screen after they have taken a couple of pictures. That shows they like the app. 

**Taking picture mode**
screenshot_20170808-115242
- I would consider making the buttons for adjusting the camera / s bigger and adding labels. They currently seem quite small and floaty. 
- The Frame around the photo area isn't consistent. I would either make it full screen or give it a 'Polaroid' frame.
- Switching cameras would be great if you 'flipped the screen' so it represents the switch.

**Photo taken mode** 
screenshot_20170808-120008
- The buttons seem very small, perhaps increase the height of the bottom bar where they sit. 
- Make the frame width consistent. OR make it full screen. 
- There seems to be a milli-second delay when I click on each tab / button / effect. 
- A reset button would be nice. So the photo returns to its original view. 
- Not sure how I save the image. 
- A tick just to confirm a save would reassure the user. 
- When I pressed 'X' Close button the screen went black and the error message below appeared. The url was /browse.
- The loading of the images is very sluggish, i would do some sort of [skeleton screen](https://developers.google.com/web/fundamentals/instant-and-offline/offline-ux#use_skeleton_layouts_with_other_feedback_mechanism) transition to make it feel more snappy and alive. 

**Photo library mode** 
- I tried to take a second photo and Chrome crashed out on me. Maybe because of the large images. 
- The two icons are very similar, one is to upload a photo the second is to take another picture, I would make them a little more distinct. 
- UPLOAD: On mobile you can't drag and drop, so don't show that screen. Go direct to the upload. Also you can use the upload arrow as the icon here.

**Comment by wibblymat** [comment]
There doesn't seem to be any issue with the work in the PR, so I'm going to merge. I've opened a new issue (#22) to track the outstanding UX issues. Thanks for the thorough review!

**Pull request merged**
